# Generated by Django 4.1.2 on 2022-10-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='resume',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='resume/'),
        ),
    ]
