# Generated by Django 4.1.2 on 2022-10-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0002_register_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='resume',
            field=models.FileField(default=None, max_length=500, null=True, upload_to=''),
        ),
    ]
