# Generated by Django 4.1.2 on 2022-10-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0003_alter_register_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='resume',
        ),
    ]
