# Generated by Django 4.1.2 on 2022-10-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0004_remove_register_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='contact',
            new_name='contact_number',
        ),
    ]
