# Generated by Django 4.1.2 on 2022-10-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0005_rename_contact_register_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='current_or_last_orginization',
            new_name='current_or_last_organization',
        ),
    ]
