# Generated by Django 4.1.2 on 2022-10-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0007_register_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Years_of_experience',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
