# Generated by Django 4.1.2 on 2022-11-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobweb', '0008_register_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='EP_no',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='LinkedIn_Profile_Page_URL',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
